<?php
// lang/en.php

return [

    /* APP */
    'app_name' => 'FamilyDocs',
    'app_subtitle' => 'Document Manager for Home Assistant',
    'app_legacy_name' => 'ex Archivio Famiglia',

    /* LANGUAGE */
    'language' => 'Language',
    'italian' => 'Italiano',
    'english' => 'English',

    /* LOGIN */
    'login' => 'Login',
    'logout' => 'Logout',
    'username' => 'Username',
    'password' => 'Password',
    'sign_in' => 'Sign in',
    'access_denied' => 'Access denied',
    'invalid_credentials' => 'Invalid credentials',
    'login_success' => 'Login successful',

    /* MENU */
    'home' => 'Home',
    'dashboard' => 'Dashboard',
    'documents' => 'Documents',
    'categories' => 'Categories',
    'users' => 'Users',
    'backup' => 'Backup',
    'info' => 'Info',
    'settings' => 'Settings',

    /* ACTIONS */
    'upload' => 'Upload',
    'upload_document' => 'Upload document',
    'upload_photo' => 'Take photo',
    'download' => 'Download',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'search' => 'Search',
    'preview' => 'Preview',
    'favorite' => 'Favorite',
    'favorites' => 'Favorites',
    'share' => 'Share',
    'temporary_link' => 'Temporary link',

    /* FORM */
    'title' => 'Title',
    'description' => 'Description',
    'notes' => 'Notes',
    'tags' => 'Tags',
    'file' => 'File',
    'category' => 'Category',
    'created_at' => 'Created at',
    'updated_at' => 'Updated at',
    'actions' => 'Actions',

    /* DASHBOARD */
    'total_documents' => 'Total documents',
    'displayed_results' => 'Displayed results',
    'no_date' => 'No date',
    'important_documents' => 'Important documents',
    'recent_documents' => 'Recent documents',
    'quick_categories' => 'Quick categories',
    'search_documents' => 'Search documents',

    /* MESSAGES */
    'no_documents' => 'No documents available',
    'no_categories' => 'No categories available',
    'no_users' => 'No users available',
    'no_backup' => 'No backups available',
    'file_not_found' => 'File not found',
    'invalid_link' => 'Invalid link',
    'expired_or_invalid_link' => 'Expired or invalid link',
    'document_deleted' => 'Document deleted',

    /* CONFIRM */
    'confirm_delete' => 'Are you sure you want to delete?',
    'confirm_restore_database' => 'Restore database from this backup?',
    'confirm_restore_files' => 'Restore files from this backup?',
    'confirm_delete_backup' => 'Delete this backup?',

    /* GENERIC */
    'operation_completed' => 'Operation completed',
    'operation_failed' => 'Operation failed',

    /* INSTALL */
    'first_setup' => 'Initial setup',
    'create_admin' => 'Create first administrator',
    'setup_completed' => 'Setup completed',

    /* THEME */
    'theme_dark' => 'Dark theme',
    'theme_light' => 'Light theme',

    /* BACKUP */
    'system' => 'System',
    'archive_backup' => 'Archive backup',
    'backup_intro' => 'Full backup of database and documents',
    'run_backup' => 'Run backup',
    'upload_backup' => 'Upload backup',
    'upload_backup_text' => 'You can upload SQL backups or compressed files generated by the system',
    'available_backups' => 'Available backups',
    'backup_completed' => 'Backup completed',
    'backup_error' => 'Backup error',
    'backup_uploaded' => 'Backup uploaded',
    'backup_upload_error' => 'Backup upload error',
    'invalid_backup_format' => 'Invalid backup format',
    'backup_deleted' => 'Backup deleted',
    'backup_not_found' => 'Backup not found',
    'database_restored_from' => 'Database restored from',
    'database_restore_error' => 'Database restore error',
    'invalid_database_backup' => 'Invalid database backup',
    'files_restored_from' => 'Files restored from',
    'files_restore_error' => 'Files restore error',
    'invalid_files_backup' => 'Invalid file backup',

    /* INFO */
    'back_to_home' => 'Back to home',
    'version' => 'Version',
    'archive_statistics' => 'Archive statistics',
    'used_space' => 'Used space',
    'author' => 'Author',
    'created_and_maintained_by' => 'Created and maintained by',
    'go_to_github_project' => 'View project on GitHub',
    'view_version_history' => 'View changelog',
    'support_project' => 'Support the project',
    'support_project_text' => 'If you like it, you can support development',
    'technical_info' => 'Technical information',
    'database' => 'Database',
    'document_storage' => 'Document storage',
    'persistent_upload' => 'Persistent upload',
    'home_assistant_addon_port' => 'Home Assistant add-on port',

];
